<?php

namespace Manblio\LivreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PossessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PossessionRepository extends EntityRepository
{
	public function findUserAndLivre($id, $livre){
		$qb = $this->createQueryBuilder('p')  //add select and array for JSON
            ->where('p.utilisateur = :utilisateur AND p.livre=:livre')
            ->setParameters(array('utilisateur' => $id, 'livre' => $livre ));
 
    return $qb->getQuery()->getResult();
 
    
	}
}
